{% set name = "napari-cupy-image-processing" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-cupy-image-processing-{{ version }}.tar.gz
  sha256: 1ff186defc0ffd69f27294d735b167ceed9b993e58fa0f0f0a38f35cbfffaefb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cupy
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops
    - napari-time-slicer
    - napari-tools-menu
    - numpy
    - python >=3.7
    - scikit-image
    - toolz
    - napari-assistant

test:
  imports:
    - napari_cupy_image_processing
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-cupy-image-processing
  summary: GPU-accelerated image processing using CUDA
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
